version: 2
updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: 'Europe/Tallinn'
    open-pull-requests-limit: 10
    groups:
      dev-dependencies:
        dependency-type: development
        update-types: [minor, patch]
      prod-dependencies:
        dependency-type: production
        update-types: [patch]
    labels:
      - dependencies
      - npm

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '06:00'
      timezone: 'Europe/Tallinn'
    open-pull-requests-limit: 5
    labels:
      - dependencies
      - github-actions
