/**
 * Phase 1 MVP schema. Mirrors planning/ARCHITECTURE.md §6.1 with the
 * modifications from ADR-0005 (users aligned to Better-Auth's expected shape;
 * session/account/verification tables added).
 *
 * Email columns are `text` with a `lower(email)` unique index. ARCHITECTURE.md
 * specifies `citext`; migrating to citext is tracked as a Phase-2 task and does
 * not block MVP correctness.
 *
 * IDs: domain entities (users, events, ...) use UUIDv7 generated in app code
 * via `uuidv7()`. Better-Auth's session/account/verification use text IDs
 * generated by Better-Auth itself.
 */
import { sql } from 'drizzle-orm';
import {
  boolean,
  index,
  integer,
  jsonb,
  numeric,
  pgTable,
  text,
  timestamp,
  uniqueIndex,
  uuid,
} from 'drizzle-orm/pg-core';
import { uuidv7 } from 'uuidv7';

const genId = () => uuidv7();
const nowTs = () => timestamp({ withTimezone: true, mode: 'date' }).defaultNow().notNull();

export const users = pgTable(
  'users',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    email: text().notNull(),
    emailVerified: boolean('email_verified').notNull().default(false),
    name: text(),
    image: text(),
    // Domain extras exposed to Better-Auth via `user.additionalFields`.
    locale: text().notNull().default('en'),
    timezone: text().notNull().default('UTC'),
    createdAt: nowTs(),
    updatedAt: nowTs(),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
  },
  (t) => [uniqueIndex('users_email_lower_idx').on(sql`lower(${t.email})`)],
);

/**
 * Better-Auth session.
 *
 * Rows are keyed by Better-Auth-generated text ids, not uuidv7. A session's
 * lifetime is independent of the user: cascading delete is correct (delete a
 * user, kill all their sessions) but we never delete sessions by user from
 * domain code — Better-Auth manages that.
 */
export const sessions = pgTable(
  'sessions',
  {
    id: text().primaryKey(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    token: text().notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    ipAddress: text('ip_address'),
    userAgent: text('user_agent'),
    createdAt: nowTs(),
    updatedAt: nowTs(),
  },
  (t) => [uniqueIndex('sessions_token_idx').on(t.token), index('sessions_user_idx').on(t.userId)],
);

export const accounts = pgTable(
  'accounts',
  {
    id: text().primaryKey(),
    accountId: text('account_id').notNull(),
    providerId: text('provider_id').notNull(),
    userId: uuid('user_id')
      .notNull()
      .references(() => users.id, { onDelete: 'cascade' }),
    accessToken: text('access_token'),
    refreshToken: text('refresh_token'),
    idToken: text('id_token'),
    accessTokenExpiresAt: timestamp('access_token_expires_at', { withTimezone: true }),
    refreshTokenExpiresAt: timestamp('refresh_token_expires_at', { withTimezone: true }),
    scope: text(),
    password: text(),
    createdAt: nowTs(),
    updatedAt: nowTs(),
  },
  (t) => [
    uniqueIndex('accounts_provider_account_idx').on(t.providerId, t.accountId),
    index('accounts_user_idx').on(t.userId),
  ],
);

export const verifications = pgTable(
  'verifications',
  {
    id: text().primaryKey(),
    identifier: text().notNull(),
    value: text().notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }).notNull(),
    createdAt: nowTs(),
    updatedAt: nowTs(),
  },
  (t) => [index('verifications_identifier_idx').on(t.identifier)],
);

export const events = pgTable(
  'events',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    slug: text().notNull(),
    title: text().notNull(),
    description: text(),
    startsAt: timestamp('starts_at', { withTimezone: true }).notNull(),
    endsAt: timestamp('ends_at', { withTimezone: true }),
    timezone: text().notNull(),
    locationText: text('location_text'),
    locationLat: numeric('location_lat', { precision: 10, scale: 7 }),
    locationLng: numeric('location_lng', { precision: 10, scale: 7 }),
    creatorEmail: text('creator_email').notNull(),
    creatorUserId: uuid('creator_user_id').references(() => users.id, {
      onDelete: 'set null',
    }),
    isPaid: boolean('is_paid').notNull().default(false),
    paidFeatures: jsonb('paid_features').notNull().default({}),
    paymentProvider: text('payment_provider'),
    paymentRef: text('payment_ref'),
    passwordHash: text('password_hash'),
    coverMediaId: uuid('cover_media_id'),
    defaultLocale: text('default_locale').notNull().default('en'),
    visibility: text().notNull().default('link_only'),
    deletedAt: timestamp('deleted_at', { withTimezone: true }),
    createdAt: nowTs(),
    updatedAt: nowTs(),
  },
  (t) => [
    uniqueIndex('events_slug_idx').on(t.slug),
    uniqueIndex('events_creator_email_lower_idx').on(sql`lower(${t.creatorEmail})`, t.id),
    index('events_creator_user_idx').on(t.creatorUserId),
    index('events_starts_at_idx').on(t.startsAt),
  ],
);

export const eventTokens = pgTable(
  'event_tokens',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    eventId: uuid('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    tokenHash: text('token_hash').notNull(),
    purpose: text().notNull(),
    expiresAt: timestamp('expires_at', { withTimezone: true }),
    revokedAt: timestamp('revoked_at', { withTimezone: true }),
    createdAt: nowTs(),
  },
  (t) => [
    uniqueIndex('event_tokens_token_hash_idx').on(t.tokenHash),
    index('event_tokens_event_idx').on(t.eventId),
  ],
);

export const guests = pgTable(
  'guests',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    eventId: uuid('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    name: text(),
    email: text(),
    phone: text(),
    invitedVia: text('invited_via').notNull(),
    invitedAt: nowTs(),
  },
  (t) => [index('guests_event_idx').on(t.eventId)],
);

export const rsvps = pgTable(
  'rsvps',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    eventId: uuid('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    guestId: uuid('guest_id').references(() => guests.id, { onDelete: 'set null' }),
    name: text().notNull(),
    email: text(),
    status: text().notNull(),
    plusOnes: integer('plus_ones').notNull().default(0),
    // Named plus-one details. Populated only for Plus-tier events (A.6b);
    // Basic-tier events keep the plusOnes count and leave this empty.
    // Shape: [{ name: string }, …]. Keep loose so we can add fields
    // (dietary, +1 email) without a schema migration.
    plusOnesDetails: jsonb('plus_ones_details').notNull().default([]),
    message: text(),
    respondedAt: nowTs(),
  },
  (t) => [index('rsvps_event_idx').on(t.eventId), index('rsvps_guest_idx').on(t.guestId)],
);

/**
 * Reminder schedule. Each row is "send a reminder for this event at this
 * time". The cron worker picks up rows where `sent_at IS NULL AND scheduled_at <= now()`,
 * sends the email, and stamps `sent_at`.
 */
export const reminders = pgTable(
  'reminders',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    eventId: uuid('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    scheduledAt: timestamp('scheduled_at', { withTimezone: true }).notNull(),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    kind: text().notNull().default('standard'),
    createdAt: nowTs(),
  },
  (t) => [
    index('reminders_due_idx').on(t.scheduledAt, t.sentAt),
    index('reminders_event_idx').on(t.eventId),
  ],
);

/**
 * Event announcements (A.6b.3). Each row represents a single bulk email
 * wave to the event's guest list at a specific stage. The unique index on
 * (event_id, stage) enforces "one Save-the-Date, one Invitation" per event;
 * re-sending requires deleting the row first (admin path — not exposed).
 */
export const eventAnnouncements = pgTable(
  'event_announcements',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    eventId: uuid('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    stage: text().notNull(), // 'save_the_date' | 'invitation'
    templateId: text('template_id'),
    sentAt: timestamp('sent_at', { withTimezone: true }),
    recipientCount: integer('recipient_count').notNull().default(0),
    createdAt: nowTs(),
  },
  (t) => [
    uniqueIndex('event_announcements_event_stage_idx').on(t.eventId, t.stage),
    index('event_announcements_event_idx').on(t.eventId),
  ],
);

/**
 * Event media — cover images + gallery entries. R2 key pattern:
 * `events/<event_id>/<media_id>.<ext>`. Deleting the event cascades; each
 * delete is responsible for also purging the R2 object (see
 * `apps/api/src/domain/media/media.ts`).
 */
export const eventMedia = pgTable(
  'event_media',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    eventId: uuid('event_id')
      .notNull()
      .references(() => events.id, { onDelete: 'cascade' }),
    r2Key: text('r2_key').notNull(),
    kind: text().notNull().default('cover'),
    mimeType: text('mime_type').notNull(),
    sizeBytes: integer('size_bytes').notNull(),
    width: integer(),
    height: integer(),
    position: integer().notNull().default(0),
    createdAt: nowTs(),
  },
  (t) => [index('event_media_event_idx').on(t.eventId)],
);

/**
 * Append-only audit log. Any side-effectful action (event write, RSVP,
 * reminder send, payment complete) gets a row. No foreign keys on
 * `event_id` so the log survives event deletion.
 */
export const auditLog = pgTable(
  'audit_log',
  {
    id: uuid().primaryKey().$defaultFn(genId),
    actorType: text('actor_type').notNull(),
    actorId: text('actor_id'),
    eventId: uuid('event_id'),
    action: text().notNull(),
    metadata: jsonb().notNull().default({}),
    ipHash: text('ip_hash'),
    createdAt: nowTs(),
  },
  (t) => [index('audit_log_event_idx').on(t.eventId), index('audit_log_action_idx').on(t.action)],
);

export type User = typeof users.$inferSelect;
export type NewUser = typeof users.$inferInsert;
export type Session = typeof sessions.$inferSelect;
export type NewSession = typeof sessions.$inferInsert;
export type Account = typeof accounts.$inferSelect;
export type NewAccount = typeof accounts.$inferInsert;
export type Verification = typeof verifications.$inferSelect;
export type NewVerification = typeof verifications.$inferInsert;
export type Event = typeof events.$inferSelect;
export type NewEvent = typeof events.$inferInsert;
export type EventToken = typeof eventTokens.$inferSelect;
export type NewEventToken = typeof eventTokens.$inferInsert;
export type Guest = typeof guests.$inferSelect;
export type NewGuest = typeof guests.$inferInsert;
export type Rsvp = typeof rsvps.$inferSelect;
export type NewRsvp = typeof rsvps.$inferInsert;
export type Reminder = typeof reminders.$inferSelect;
export type NewReminder = typeof reminders.$inferInsert;
export type EventMedia = typeof eventMedia.$inferSelect;
export type NewEventMedia = typeof eventMedia.$inferInsert;
export type EventAnnouncement = typeof eventAnnouncements.$inferSelect;
export type NewEventAnnouncement = typeof eventAnnouncements.$inferInsert;
export type AuditLog = typeof auditLog.$inferSelect;
export type NewAuditLog = typeof auditLog.$inferInsert;

export const schema = {
  users,
  sessions,
  accounts,
  verifications,
  events,
  eventTokens,
  guests,
  rsvps,
  reminders,
  eventMedia,
  eventAnnouncements,
  auditLog,
};
